[package]
name = "file-open"
version = "0.1.0"
authors = ["YesSeri <henrik.zenkert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "2.0.0"
clap = "2.33.3"
walkdir = "2.3.2"
crossterm = "0.20.0"
